Fix api call to get_deployment_status
Function get_deployment_status requires the stack_name parameter, cannot pass plan=plan

Without fix, getting this error:

openstack tripleo validator run --group pre-update-prepare --plan overcloud
get_deployment_status() got an unexpected keyword argument 'plan'

Co-authored-by: Daniel Bengtsson <dbengt@redhat.com>
Change-Id: I7b5da62a564c22738427632ea03b1e33cdf2f89a